version: "3.9"
services:
  account_app:
    build:
      context: ./services/account
      dockerfile: Dockerfile.app
    depends_on:
      - postgres
      - pubsub
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/gcloud/google-application-credentials.json
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=account
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PUBSUB_PROJECT_ID=jads-adaassignment
    volumes:
      - ./google-application-credentials.json:/opt/gcloud/google-application-credentials.json
      - ./services/account/src:/opt/service/src

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/postgres.sh:/docker-entrypoint-initdb.d/postgres.sh

  pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
