FROM python:3.9-slim

# Copy requirements
COPY requirements.txt /opt/service/requirements.txt

# Copy source code
COPY src /opt/service/src

# Install requirements
RUN pip install -r /opt/service/requirements.txt

# Set python path
ENV PYTHONPATH=/opt/service/src

# Set working directory
WORKDIR /opt/service

# Run worker
ENTRYPOINT ["huey_consumer", "communication.__main__.worker"]
CMD ["--workers", "1", "--worker-type", "thread"]
